file <- paste(getwd(), "household_power_consumption.txt", sep="/")
data <- read.table(file, header=TRUE, sep=";")
df <- data.frame(data)
df$Date <- as.Date(df$Date, "%d/%m/%Y")
sub <- subset(df, df$Date=="2007-02-01" | df$Date=="2007-02-02")
sub$Global_active_power <- as.numeric(as.character(sub$Global_active_power))
date_time <- paste(sub$Date, sub$Time)
x <- strptime(date_time, format="%Y-%m-%d %H:%M:%S")
y <- as.numeric(as.character(sub$Sub_metering_1))
z <- as.numeric(as.character(sub$Sub_metering_2))
a <- as.numeric(as.character(sub$Sub_metering_3))
png(filename=paste(getwd(), "plot3.png", sep="/"), width=480, height=480, units="px")
plot(x,y, type="l", ylab="Energy sub metering", xlab="")
lines(x,a, col="blue")
lines(x,z, col="red")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(1, 1, 1),col=c("black","red","blue"), cex=.75)
dev.off()