file <- paste(getwd(), "household_power_consumption.txt", sep="/")
data <- read.table(file, header=TRUE, sep=";")
df <- data.frame(data)
df$Date <- as.Date(df$Date, "%d/%m/%Y")
sub <- subset(df, df$Date=="2007-02-01" | df$Date=="2007-02-02")
sub$Global_active_power <- as.numeric(as.character(sub$Global_active_power))
date_time <- paste(sub$Date, sub$Time)
x <- strptime(date_time, format="%Y-%m-%d %H:%M:%S")
png(file="plot4.png")
par(mfrow=c(2,2))
y <- as.numeric(as.character(sub$Global_active_power))
plot(x,y,type="l",ylab="Global Active Power (kilowatts)",xlab="")
y <- as.numeric(as.character(sub$Voltage))
plot(x,y,type="l",ylab="Voltage",xlab="datetime")
y <- as.numeric(as.character(sub$Sub_metering_1))
plot(x,y, type="l", ylab="Energy sub metering", xlab="")
lines(x,a, col="blue")
lines(x,z, col="red")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(1, 1, 1),col=c("black","red","blue"), cex=.75)
y <- as.numeric(as.character(sub$Global_reactive_power))
plot(x,y,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()