file <- paste(getwd(), "household_power_consumption.txt", sep="/")
data <- read.table(file, header=TRUE, sep=";")
df <- data.frame(data)
df$Date <- as.Date(df$Date, "%d/%m/%Y")
sub <- subset(df, df$Date=="2007-02-01" | df$Date=="2007-02-02")
sub$Global_active_power <- as.numeric(as.character(sub$Global_active_power))
png(filename=paste(getwd(), "plot1.png", sep="/"), width=480, height=480, units="px")
hist(sub$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()